// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllDownloadPhotos(arg1) {
  return window['go']['infraui']['app']['AllDownloadPhotos'](arg1);
}

export function Cancel() {
  return window['go']['infraui']['app']['Cancel']();
}

export function Code2fa(arg1) {
  return window['go']['infraui']['app']['Code2fa'](arg1);
}

export function LoginICloud(arg1, arg2) {
  return window['go']['infraui']['app']['LoginICloud'](arg1, arg2);
}

export function Run() {
  return window['go']['infraui']['app']['Run']();
}

export function SelectDirectory() {
  return window['go']['infraui']['app']['SelectDirectory']();
}
