// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllDownloadPhotos(arg1:string):Promise<string>;

export function Cancel():Promise<void>;

export function Code2fa(arg1:string):Promise<string>;

export function LoginICloud(arg1:string,arg2:string):Promise<string>;

export function Run():Promise<void>;

export function SelectDirectory():Promise<string>;
