// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllDownloadPhotos(arg1) {
  return window['go']['ui']['App']['AllDownloadPhotos'](arg1);
}

export function Cancel() {
  return window['go']['ui']['App']['Cancel']();
}

export function Code2fa(arg1) {
  return window['go']['ui']['App']['Code2fa'](arg1);
}

export function LoginICloud(arg1, arg2) {
  return window['go']['ui']['App']['LoginICloud'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['ui']['App']['SelectDirectory']();
}
